server:
  port: 8080

#develop
frontDomain: "http://localhost:3000"
dbDomain: "mysql://localhost:3306"
#deploy
#frontDomain: "http://54.180.92.229:3000"
#dbDomain: "mysql://43.200.180.97:3306"
dbUser: "root"
dbPasswd: "1234"

spring:
  datasource:
    url: jdbc:${dbDomain}/reactdemo?useSSL=false&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Seoul
    username: ${dbUser}
    password: ${dbPasswd}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  issuer: reactdemo
  secret-key: jwtSecretKey